### ISSUE TITLE
Could not read Username

### ISSUE THREAD

**Issue by edionmelarosa** [Cecilapp/GitHub-Pages-deploy#11]
Im getting this error. when deploying.

`fatal: could not read Username for 'https://github.com': No such device or address`

here's my yml config:

```yaml
name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: edion.larosa@gmail.com
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: dist/
```
