### ISSUE TITLE
master branch overwritten with gh-pages branch?

### ISSUE THREAD

**Issue by reptile18** [Cecilapp/GitHub-Pages-deploy#13]
Tried using this action and it ended up deleting everything in my master branch and setting it to be identical to my gh-pages branch.

**Comment by reptile18** [comment]
This is what I was using in main.yml:
```yml
- name: GH Pages deploy
      # You may pin to the exact commit or the version.
      # uses: Cecilapp/GitHub-Pages-deploy@10c15d01fe8f5100fdcc07f1568fe94bfa7b7d4c
      uses: Cecilapp/GitHub-Pages-deploy@2.0.1
      env: 
        EMAIL: reptile18@gmail.com
        GH_TOKEN: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
        BUILD_DIR: public
```
