### ISSUE TITLE
cp: can't stat '_site/*': No such file or directory error (as of today)

### ISSUE THREAD

**Issue by jtr13** [Cecilapp/GitHub-Pages-deploy#15]
Thank you for this action, it's been working great. Now the deploy however is no longer working. I am using GH secrets. Here's an example of the fail log:

https://github.com/jtr13/myproject/actions/runs/416822617

Any help would be appreciated!

**Comment by ArnaudLigny** [comment]
Hello Joyce, it' because you are using the new version (3.x.x) of the Action but with the previous configuration.

The Action now use inputs instead of variables (excepted for the token).

Could you try this?

```
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: ${{ secrets.EMAIL }}
        build_dir: _book
```
