### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by isaactpetersen** [Cecilapp/GitHub-Pages-deploy#21]
I receive the following warning when using the `Cecilapp/GitHub-Pages-deploy@v3` action:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Here's my full workflow file:

```
on:
  push:
     branches:
       - main

name: deploywebsite

jobs:
  rmarkdown:
    name: Render-Website
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Session info
        run: Rscript -e 'sessionInfo()'

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render blog
        run: Rscript -e 'rmarkdown::render_site()'

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site/

  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: rmarkdown
   steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
         # Artifact name
         name: site
         # Destination path
         path: _site

     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          build_dir: _site/
          email: ${{ secrets.EMAIL }}
```

Here is the relevant portion of the GitHub Actions log:

```
Run Cecilapp/GitHub-Pages-deploy@v3
  with:
    build_dir: _site/
    email: ***
    jekyll: no
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name bedb4f3[2](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:2)7cda84b8940b8b680fad514dd7[3](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:3)fe_ef13[4](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:4)c --label [5](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:5)bedb4 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "INPUT_BUILD_DIR" -e "INPUT_EMAIL" -e "INPUT_BRANCH" -e "INPUT_CNAME" -e "INPUT_JEKYLL" -e "INPUT_COMMIT_MESSAGE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/LabWiki/LabWiki":"/github/workspace" 5bedb4:f327cda84b8940b8b[6](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:6)80fad514dd[7](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:7)3fe
Starting deploy to DevPsyLab/LabWiki/gh-pages
Configuration:
- email: ***
- build_dir: _site/
- cname: 
- Jekyll: no
Clone branch 'gh-pages'
[gh-pages [9](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:10)4d94ad] isaactpetersen published a site update
 22 files changed, 35 insertions(+), 35 deletions(-)
 rename site_libs/{header-attrs-2.23 => header-attrs-2.24}/header-attrs.js ([10](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:11)0%)
Deploy succeeded
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-[11](https://github.com/DevPsyLab/LabWiki/actions/runs/5858472724/job/15882955898#step:5:12)-github-actions-deprecating-save-state-and-set-output-commands/
```
