### ISSUE TITLE
BUILD_DIR value for this task in release section

### ISSUE THREAD

**Issue by ClydeDz** [Cecilapp/GitHub-Pages-deploy#6]
Hi,

Thanks for creating this action. I used it successfully in my build section with the following configuration.

```yml
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: ${{ secrets.EMAIL }} 
        GH_TOKEN: ${{ secrets.PAT }}  
        BUILD_DIR: build/
```

However, when I moved this to the release section, I got the error below. 
![image](https://user-images.githubusercontent.com/13506613/73134668-526b5e00-409e-11ea-8fdc-febe03cb3398.png)

What would I need to write against the `BUILD_DIR` key? I was under the assumption that the build section would still build the app and generate the files and folder and the release section can pick up any folder from there?

Cheers!
