### ISSUE TITLE
git authenticate error.

### ISSUE THREAD

**Issue by liudonghua123** [Cecilapp/GitHub-Pages-deploy#9]
If I use the buildin `GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}`, then I got the authenticate errors. 

After read the doc, I think the correct method of setting authenticate is using the form `https://${GITHUB_ACTOR}:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git`, not `https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git`, the former is compatible with repository scoped tokens like `GITHUB_TOKEN`.

more details can be found on:

- https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
- https://stackoverflow.com/questions/18935539/authenticate-with-github-using-a-token

**Comment by ArnaudLigny** [comment]
Hello @liudonghua123, could you share the error message? Username is not required with token.

**Comment by liudonghua123** [comment]
@Narno , Hi, It's really strange, I reverted the github actions, but the error disappeared, detailed logs are in https://github.com/liudonghua123/wayfless_generator_flutter/runs/500496978?check_suite_focus=true. The previous error logs are deleted when I modified the `entrypoint.sh` and rerun the workflow.
And the deploy steps are:
```
      - name: Deploy to GitHub Pages
        uses: liudonghua123/GitHub-Pages-deploy@'fix-multi-level-BUILD_DIR'
        env:
          EMAIL: liudonghua123@gmail.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: ./build/web/
```
